### PR TITLE
test

### PR DESCRIPTION
**Pull request by lcarva**
Signed-off-by: Luiz Carvalho <lucarval@redhat.com>

### CODE REVIEW

**Comment by lcarva** [comment]
ugh... chains (0.14.0) is still somehow failing to push signatures due to unauthorized error.

**Comment by lcarva** [comment]
@Michkov, I noticed that the secret for the pipeline SA is only listed under `secrets`. Chains wants it to be under `imagePullSecrets`. Is this something we can just manually update, or is it done by some service?

**Comment by Michkov** [comment]
@lcarva I think that for testing purpose we can manually update and if it will work then update https://github.com/redhat-appstudio/infra-deployments/blob/main/components/tekton-ci/serviceaccount.yaml .

**Comment by lcarva** [comment]
Chains is now signing the image. However, ArgoCD is having issues synchronizing one of the modified resources.

**Pull request closed without merging**
